name: Scheduled workflow for lighthouse CI
on:  
  schedule:  
    - cron:  '*/10 * * * *'    # At every 10 minute
jobs:  
  scheduledJobForLightHouseCI:  
    runs-on: ubuntu-latest    
    steps:       
      - uses: actions/checkout@v3  
        with:  
          ## We checkout not the head of the `master` branch 
          ## but the exact commit where the scheduling happened. 
          ## This env variable contains SHA (or tag name) of the 
          ## commit which triggered our main workflow.
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }}
        
      - name: Check the staging version in every 20 minutes
        run: |
          response=$(curl -X GET "https://lite-stage-de.flaconi.de/api/version" | jq -r '.version')
          echo stagingVersion="$response" >> $GITHUB_ENV
          echo "stagingVersion is $stagingVersion"

      ## When staging deployment is completed then run lighthouse CI
      - name: lighthouse CI
        id: lighthouseCI
        if: ${{ env.DELAYED_JOB_PAYLOAD == env.stagingVersion }}
      ## continue-on-error: true
        run: echo "The version is same $stagingVersion"
        
        ## This means the if expression did not match
      - name: lighthouse CI if expression testing
        if: ${{ env.DELAYED_JOB_PAYLOAD != env.stagingVersion }}
      ## continue-on-error: true
        run: echo "The version is not same $stagingVersion"
        
      - name: Just testing step
        run: echo This is from delayed file after 3 minutes and the variable is ${{ env.DELAYED_JOB_PAYLOAD }}

      ## Remove the workflow file from `.github/workflows` 
      ## if work step has succeeded or attempts number 
      ## has reached the limit equal to 3
      - name: Remove scheduled job
        if: |
          steps.lighthouseCI.outcome == 'success' || 
          github.run_number > 3
        uses: cardinalby/unschedule-job-action@v1  
        with:  
          ghToken: ${{ secrets.PERSONAL_TOKEN }}
