name: example-cron-action
'on':
  schedule:
    - cron: '*/5 * * * *'
jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: Fake work
        id: actualWorkStep
        continue-on-error: true
        run: exit 1
      - name: Just testing step
        run: echo This is from delayed file after 3 minutes
      - name: Remove scheduled job
        if: github.run_number > 2
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.PERSONAL_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: 6ce067647780f4427d42a7df1ce72febaf39623f
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/example-6ce067647780f4427d42a7df1ce72febaf39623f.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: master
      DELAYED_JOB_PAYLOAD: 2022.07.13.07.14
