name: Scheduled workflow
'on':
  schedule:
    - cron: '*/3 * * * *'
jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: Fake work
        id: actualWorkStep
        continue-on-error: true
        run: exit 1
      - name: Just testing step
        run: >-
          echo This is from delayed file after 3 minutes and the variable is ${{
          env.DELAYED_JOB_PAYLOAD }}
      - name: Remove scheduled job
        if: github.run_number > 200
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.PERSONAL_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: a72011c44f1dd77a074d22cf035db430fb651ca7
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/example-a72011c44f1dd77a074d22cf035db430fb651ca7.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: master
      DELAYED_JOB_PAYLOAD: 2022.07.13.07.14
