name: Scheduled workflow for lighthouse CI
'on':
  schedule:
    - cron: '*/10 * * * *'
jobs:
  scheduledJobForLightHouseCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: Check the staging version in every 20 minutes
        run: >
          response=$(curl -X GET "https://lite-stage-de.flaconi.de/api/version"
          | jq -r '.version')

          echo stagingVersion="$response" >> $GITHUB_ENV

          echo "stagingVersion is $stagingVersion"
      - name: lighthouse CI
        id: stagingDeploymentStatus
        if: '${{ env.DELAYED_JOB_PAYLOAD == env.stagingVersion }}'
        run: echo "deploymentCompleted=true" >> $GITHUB_ENV
      - name: Use Node.js 14.x
        if: '${{ env.deploymentCompleted == ''true'' }}'
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
      - name: install puppeteer
        if: '${{ env.deploymentCompleted == ''true'' }}'
        run: yarn add puppeteer --dev --immutable
      - name: run Lighthouse CI
        if: '${{ env.deploymentCompleted == ''true'' }}'
        run: |
          yarn global add @lhci/cli@0.8.x
          lhci autorun || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: '${{ secrets.LHCI_GITHUB_APP_TOKEN }}'
          LHCI_WIZARD_BUILD_TOKEN: '${{ secrets.LHCI_WIZARD_BUILD_TOKEN }}'
          LHCI_STAGING_ENVIRONMENT_USERNAME: '${{ secrets.LHCI_STAGING_ENVIRONMENT_USERNAME }}'
          LHCI_STAGING_ENVIRONMENT_PASSWORD: '${{ secrets.LHCI_STAGING_ENVIRONMENT_PASSWORD }}'
      - name: Remove scheduled job
        if: |
          steps.stagingDeploymentStatus.outcome == 'success' || 
          github.run_number > 3
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.PERSONAL_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: 587e2d83a272bcc593a2e6af3c11dd072e3d2682
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/scheduledWorkFlowTemplate-587e2d83a272bcc593a2e6af3c11dd072e3d2682.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: master
      DELAYED_JOB_PAYLOAD: 2022.07.13.07.14
