name: Scheduled workflow for lighthouse CI
'on':
  schedule:
    - cron: '*/10 * * * *'
jobs:
  scheduledJobForLightHouseCI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: Check the staging version in every 20 minutes
        run: >
          response=$(curl -X GET "https://lite-stage-de.flaconi.de/api/version"
          | jq -r '.version')

          echo stagingVersion="$response" >> $GITHUB_ENV

          echo "stagingVersion is $stagingVersion"
      - name: lighthouse CI
        id: lighthouseCI
        if: '${{ env.DELAYED_JOB_CHECKOUT_REF == env.stagingVersion }}'
        run: echo "The version is same $stagingVersion"
      - name: lighthouse CI if expression testing
        if: '${{ env.DELAYED_JOB_CHECKOUT_REF != env.stagingVersion }}'
        run: echo "The version is not same $stagingVersion"
      - name: Just testing step
        run: >-
          echo This is from delayed file after 3 minutes and the variable is ${{
          env.DELAYED_JOB_PAYLOAD }}
      - name: Remove scheduled job
        if: |
          steps.lighthouseCI.outcome == 'success' || 
          github.run_number > 3
        uses: cardinalby/unschedule-job-action@v1
        with:
          ghToken: '${{ secrets.PERSONAL_TOKEN }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: 27f6079bce8455932e6eafe863da873c0b715823
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/scheduledWorkFlowTemplate-27f6079bce8455932e6eafe863da873c0b715823.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: master
      DELAYED_JOB_PAYLOAD: 2022.07.13.07.14
