# This is a basic workflow to help you get started with Actions.

name: new method

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 180

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
             ref: ${{ github.event.inputs.branch }}
             fetch-depth: 0
      # - uses: './.github/workflows/composite-action'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: ${{ github.event_name != 'schedule' }}
        run: echo Hello from not a schedule!
        
      # If it is schedule task
      - name: Run a one-line script
        if: ${{ github.event_name == 'schedule' }}
        run: echo Hello from schedule!

      
      - name: get output
        run: echo ${{ steps.branch-name.outputs }}
          


